[project]
name = "playwrightscraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "dbml-sqlite>=0.3.3",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "playwright>=1.53.0",
    "pyodbc>=5.2.0",
    "sqlalchemy>=2.0.42",
    "tenacity>=9.1.2",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.0",
]
