[[student]]
id         = "jacob.415195"
password   = "Mr.Farts12!"
portal     = "infinite_campus_student_ccsd"

[[student]]
id         = "tommie.2339212"
password   = "MphH!5!72U"
portal     = "infinite_campus_student_ccsd"          # will wire this later